project:
  type: book
  output-dir: docs
book:
  title: R в социологических исследованиях (2-е издание)
  author:
    name: Дарья Омельченко
    affiliation: "Институт гуманитарных наук, Алтайский государственный университет"
    url: "https://www.asu.ru/persons/484/"
    orcid: 0000-0002-2839-5070
    github: "domelia"
    email: omelchenko@socio.asu.ru
  search: true
  repo-url: https://github.com/domelia/R-book-2026/
  repo-actions: edit
  page-footer:
    left: |
      R в социологических исследованиях (2-e издание), Д. А. Омельченко (ИГН АлтГУ)
      Çetinkaya-Rundel, and Garrett Grolemund.
    right: |
      Эта книга написана с помощью <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.jpg
  chapters:
  - index.qmd
  - About-R.qmd
  - Install-R.qmd
  - Data-types-and-structures.qmd
  - Intro-to-RMarkdown.qmd
  - Functions.qmd
  - ImportExport.qmd
  - TidyverseTransformations.qmd
  - Base_ggplot2.qmd
  - ExploratoryDataAnalysis.qmd
  - Statistical-Inference.qmd
  - PCA_CA.qmd
  - Regression.qmd
  - references.qmd
lang: ru
comments:
  hypothesis: true
bibliography: references.bib
format:
  html:
    theme: Pulse
    css: include/webex.css
    include-after-body: include/webex.js
    embed-resources: false
    code-overflow: wrap
editor: visual
